import Header from '@/components/layout/Header'
import type { Metadata } from 'next'
import 'remixicon/fonts/remixicon.css'
import './globals.css'

/**메타 데이터 설정 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
