import SideBar from '@/components/layout/SideBar'
import type { Metadata } from 'next'
import 'remixicon/fonts/remixicon.css'
import './globals.css'

/**메타 데이터 설정 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="flex flex-row gap-5 p-5">
          <SideBar />
          <div className="flex w-full flex-col rounded-md bg-white shadow-lg">
            <div className="p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
